  var EXAMS = {
    dp: {
      key: "dp",
      title: "Data Privacy Practice",
      subtitle: "Sprint 1.4 · Unit 1: Technology, IP and Security · DigiChamps Level 10",
      classes: ["10AM1","10AM2","10AM3","10AM4","10AM5","10AM6"],
      sectionA: { label: "Multiple choice", count: 20 },
      sectionB: { label: "True / False", count: 10 },
      hasGrade: false,
      questions: [
        // ---------------- MULTIPLE CHOICE (20) ----------------
        { type:"mcq", q:"Which best describes “automated data collection”?", options:["Collecting data automatically, often without users’ full knowledge or consent","A method where users manually approve every single data point collected","A process that only happens with written government permission","Deleting user data automatically after every session"], correct:0, explain:"Automated data collection can happen quietly in the background — for example, apps mining account activity or cameras analysing shopper behaviour — often without people realising it.", topic:"Automated Data Collection" },
        { type:"mcq", q:"Which organisation was accused in 2018 of harvesting data from up to 87 million Facebook users without their consent?", options:["Yahoo","Cambridge Analytica","Microsoft","The Network Advertising Initiative"], correct:1, explain:"Cambridge Analytica combined this data with voter information and psychological profiling to target political ads and influence public opinion.", topic:"Cambridge Analytica Case" },
        { type:"mcq", q:"How did Cambridge Analytica initially obtain much of its data?", options:["Through a personality-quiz app connected to Facebook’s API","By hacking government servers","Through a public records request","From a leaked Yahoo database"], correct:0, explain:"The app could access data from people who took the quiz and, through the same permission, data about their friends too — even without the friends' own consent.", topic:"Cambridge Analytica Case" },
        { type:"mcq", q:"What is “profiling” in a data-privacy context?", options:["Verifying someone’s identity with a photo ID","Encrypting a user’s personal files","Analysing personal data to categorise or predict someone’s behaviour and preferences","Deleting inactive accounts"], correct:2, explain:"Profiling uses information such as browsing history, purchases, and demographics to make predictions — it's behind things like targeted ads and credit scoring.", topic:"Profiling & Surveillance" },
        { type:"mcq", q:"Which of these is an example of profiling described in the material?", options:["Browsing for a t-shirt online and then seeing more shirt ads afterward","Receiving a routine software update notification","Getting a two-factor authentication code by text","A teacher grading an exam"], correct:0, explain:"This is a common result of profiling: past browsing and purchase behaviour shapes the ads a person is shown later.", topic:"Profiling & Surveillance" },
        { type:"mcq", q:"What is one privacy concern with surveillance cameras in stores and on roads?", options:["They cannot legally be installed","People are often unaware their behaviour is being recorded and analysed","They only work during business hours","They require the subject’s written consent every time"], correct:1, explain:"Even when footage seems anonymous, video analytics can still connect it to habits, appearances, and other identifying details.", topic:"Profiling & Surveillance" },
        { type:"mcq", q:"Why does data privacy matter for individual freedom, according to the material?", options:["It lets people control what personal information they share and with whom","It has no connection to personal freedom","It only benefits large corporations","It is solely a legal formality with no real impact"], correct:0, explain:"Privacy lets people set boundaries around their information; without it, trust in relationships and institutions can break down.", topic:"Legal, Social & Economic Implications" },
        { type:"mcq", q:"What challenge do differing global privacy laws create for international companies?", options:["None — all countries follow the exact same rules","Conflicting compliance and enforcement requirements across regions","Companies are banned from collecting any data","It eliminates the need for privacy policies"], correct:1, explain:"Some countries regulate data collection tightly while others favour open access, creating incompatible standards for companies operating across borders.", topic:"Legal, Social & Economic Implications" },
        { type:"mcq", q:"Which of the following is listed as a POSITIVE impact of data use?", options:["Identity theft","Enhanced personalisation of products and services","Discrimination and bias","Widening the digital divide"], correct:1, explain:"Data lets companies understand customer needs closely enough to build more personalised, satisfying products and services.", topic:"Ethical Perspectives (Pros & Cons)" },
        { type:"mcq", q:"Which of the following is listed as a NEGATIVE impact of data misuse?", options:["Improved decision-making","Economic growth","Vulnerability to fraud and identity theft","Better public services"], correct:2, explain:"Sensitive data that is poorly managed can be exploited for fraud, identity theft, and manipulation.", topic:"Ethical Perspectives (Pros & Cons)" },
        { type:"mcq", q:"What does “digital divide” refer to in this context?", options:["A disagreement between two tech companies","Growing inequity for people who lack access to, or literacy with, digital tools","A type of data encryption","A privacy law passed in one country"], correct:1, explain:"As more opportunities depend on data and digital access, people without that access or know-how risk being left further behind.", topic:"Ethical Perspectives (Pros & Cons)" },
        { type:"mcq", q:"What is a data breach?", options:["A scheduled software update","Unauthorised access to, sharing of, or theft of sensitive or protected information","A backup copy of a database","A new privacy regulation"], correct:1, explain:"Breaches can happen through cyberattacks, theft, or simple human error, and can expose personal information on a massive scale.", topic:"Data Breaches" },
        { type:"mcq", q:"Which company’s breach (occurring 2013–2016) exposed data from over 3 billion accounts?", options:["Microsoft","Yahoo","Cambridge Analytica","A retail surveillance company"], correct:1, explain:"The exposed data included names, emails, phone numbers, birth dates, passwords, and security questions.", topic:"Data Breaches" },
        { type:"mcq", q:"The Microsoft Exchange email server attack affected roughly how many US organisations?", options:["About 30,000, from small businesses to local governments","Exactly 100 large corporations only","No real organisations","Only individual home users"], correct:0, explain:"The attack gave hackers access to email accounts across a wide range of organisations, not just large enterprises.", topic:"Data Breaches" },
        { type:"mcq", q:"In the Activity, someone creates a fake Facebook account using Eric’s name and photo. This is best described as:", options:["A form of identity theft / impersonation","A standard security feature","A type of two-factor authentication","A coincidence with no privacy impact"], correct:0, explain:"The impersonator could deceive Eric's contacts and misuse his identity, which is a serious privacy and reputational harm.", topic:"Real-World Scenarios" },
        { type:"mcq", q:"According to the suggested solution, what should Eric do first about the fake account?", options:["Report the fake account to Facebook","Delete his real account","Give the impersonator his login details to “prove” he's real","Ignore it — it will resolve itself"], correct:0, explain:"Reporting the impersonating account is the first recommended step, along with warning friends and reviewing his own privacy settings.", topic:"Real-World Scenarios" },
        { type:"mcq", q:"What is recommended when you must use sensitive services (like banking) on public Wi-Fi?", options:["Turn off your phone’s lock screen","Use a Virtual Private Network (VPN) to encrypt your connection","Share the Wi-Fi password with more people","Disable your antivirus software"], correct:1, explain:"Public Wi-Fi is vulnerable to hacking, and a VPN encrypts your traffic so it's harder to intercept.", topic:"Protecting Your Privacy" },
        { type:"mcq", q:"In Challenge 1, which feature helps stop unauthorised people from accessing Ms. Anna’s new phone?", options:["Screen lock (PIN, password, pattern, or biometric)","Uninstalling every app","Turning on location services for all apps","Disabling all passwords for convenience"], correct:0, explain:"A secure screen lock is one of the most basic and effective ways to prevent unauthorised access to a device.", topic:"Real-World Scenarios" },
        { type:"mcq", q:"In Challenge 2, how can John reduce the targeted ads he keeps seeing?", options:["Adjust ad-personalisation settings and use privacy tools like ad blockers","Buy more items so the algorithm “gives up”","Post his personal data publicly","Permanently disconnect his phone from the internet"], correct:0, explain:"Turning off ad personalisation where available, using ad blockers, and clearing cookies all help reduce targeted advertising.", topic:"Real-World Scenarios" },
        { type:"mcq", q:"In Challenge 3, what is the first step recommended for Sophia to audit her social media privacy?", options:["Delete every social media account","List all the platforms she’s active on and review each one’s privacy settings","Make every post public so she can “see what happens”","Share her passwords with close friends for backup"], correct:1, explain:"Auditing starts with knowing exactly which platforms you use, then reviewing each one’s privacy policy and settings.", topic:"Real-World Scenarios" },

        // ---------------- TRUE / FALSE (10) ----------------
        { type:"tf", q:"Automated data collection can happen without users being aware of it or giving explicit consent.", options:["True","False"], correct:0, explain:"Examples include social platforms mining account data quietly and surveillance cameras analysing behaviour without direct notice.", topic:"Automated Data Collection" },
        { type:"tf", q:"The people whose data Cambridge Analytica used had all given full, informed consent for that use.", options:["True","False"], correct:1, explain:"The data was collected and used without the knowledge or permission of most of the people affected — including friends of quiz-takers.", topic:"Cambridge Analytica Case" },
        { type:"tf", q:"Profiling is used only for harmful purposes and has no legitimate applications.", options:["True","False"], correct:1, explain:"Profiling also supports legitimate uses like fraud detection and personalised recommendations, alongside real risks like discrimination.", topic:"Profiling & Surveillance" },
        { type:"tf", q:"Because surveillance footage is often anonymous, it can never be used to identify or target specific individuals.", options:["True","False"], correct:1, explain:"Video analytics can still connect footage to habits, appearances, and other identifying details, even without a name attached.", topic:"Profiling & Surveillance" },
        { type:"tf", q:"Data privacy laws and regulations differ from country to country based on social, economic, and cultural factors.", options:["True","False"], correct:0, explain:"Some countries regulate data collection tightly to protect privacy, while others favour open data access to encourage innovation.", topic:"Legal, Social & Economic Implications" },
        { type:"tf", q:"Government use of data for public-safety purposes is mentioned as one of the positive impacts of data use.", options:["True","False"], correct:0, explain:"Improved crime prevention, emergency response, and security outcomes are listed as potential benefits, alongside the risks of excessive surveillance.", topic:"Ethical Perspectives (Pros & Cons)" },
        { type:"tf", q:"The Yahoo breach (2013–2016) is described as one of the largest data breaches in history.", options:["True","False"], correct:0, explain:"It affected over 3 billion accounts, exposing details like names, emails, phone numbers, and passwords.", topic:"Data Breaches" },
        { type:"tf", q:"Using the same simple password for every account is a recommended way to protect your privacy.", options:["True","False"], correct:1, explain:"Unique, complex passwords for each account are recommended instead — reused passwords put every account at risk if just one is exposed.", topic:"Protecting Your Privacy" },
        { type:"tf", q:"Enabling two-factor (multi-factor) authentication adds an extra layer of security beyond a password alone.", options:["True","False"], correct:0, explain:"It requires a second form of verification, such as a code sent to your phone, making accounts harder to break into.", topic:"Protecting Your Privacy" },
        { type:"tf", q:"Regularly updating your devices and apps has no real effect on protecting your privacy or security.", options:["True","False"], correct:1, explain:"Updates often include security patches that close vulnerabilities attackers could otherwise exploit.", topic:"Protecting Your Privacy" }
      ]
    },
    igcse: {
      key: "igcse",
      title: "IGCSE Computer Science 0478 Practice",
      subtitle: "Paper 2 · Selection (IF / CASE) statements & the Program Development Life Cycle",
      classes: ["10BR1","10BR2","10BR3"],
      sectionA: { label: "Conditional Statements (Selection)", count: 10 },
      sectionB: { label: "System Development Life Cycle", count: 10 },
      hasGrade: true,
      questions: [
        // ---------------- SECTION A: Conditional Statements / Selection (10) ----------------
        { type:"mcq", q:"Which of these is the correct pseudocode structure for a simple selection statement with only one possible outcome (no alternative action)?", options:["IF condition THEN\n    statement\nENDIF","IF condition THEN\n    statement\nELSE\nENDIF","IF (condition)\n    statement\nEND","WHILE condition THEN\n    statement\nENDWHILE"], correct:0, explain:"In 0478 pseudocode a single-branch IF only needs IF <condition> THEN <statement(s)> ENDIF. ELSE is optional and only appears when there is an alternative action to perform.", topic:"IF Statement Syntax", difficulty:"easy" },
        { type:"mcq", q:"Study the pseudocode extract below. What is the output when the value entered for Age is 18?", code:"INPUT Age\nIF Age >= 18 THEN\n    OUTPUT \"Adult\"\nELSE\n    OUTPUT \"Minor\"\nENDIF", options:["Adult","Minor","The program produces an error","Nothing is output"], correct:0, explain:"The operator >= means 'greater than or equal to', so the boundary value itself is included. Since 18 >= 18 is TRUE, \"Adult\" is output.", topic:"Relational Operators", difficulty:"easy" },
        { type:"mcq", q:"Study the nested IF statement below. What is output when Score = 85?", code:"INPUT Score\nIF Score >= 70 THEN\n    IF Score >= 90 THEN\n        OUTPUT \"A*\"\n    ELSE\n        OUTPUT \"A\"\n    ENDIF\nELSE\n    OUTPUT \"B or below\"\nENDIF", options:["A*","A","B or below","The program does not output anything"], correct:1, explain:"85 >= 70 is TRUE, so the program enters the outer IF branch. Inside it, 85 >= 90 is FALSE, so the inner ELSE runs, outputting \"A\".", topic:"Nested IF Statements", difficulty:"hard", hint:"Work from the outside in. First test the OUTER condition, Score >= 70 — decide if that's true or false for 85. Only once you know which branch you're in should you test the INNER condition against that same Score value." },
        { type:"mcq", q:"Which keyword correctly closes a CASE OF statement in 0478 pseudocode?", options:["ENDCASE","ENDOF","ENDIF","STOP CASE"], correct:0, explain:"A CASE OF selection statement always ends with ENDCASE, in the same way an IF statement ends with ENDIF.", topic:"CASE Statements", difficulty:"easy" },
        { type:"mcq", q:"In Cambridge 0478 pseudocode, which symbol represents the relational operator 'not equal to'?", options:["!=","<>","><","NOT ="], correct:1, explain:"The Cambridge pseudocode guide uses <> for 'not equal to'. The symbol != is used in languages such as Python, but not in 0478 pseudocode.", topic:"Relational Operators", difficulty:"easy" },
        { type:"mcq", q:"Study the pseudocode below. For which value of Age will \"Teenager\" NOT be output?", code:"IF Age > 12 AND Age < 20 THEN\n    OUTPUT \"Teenager\"\nENDIF", options:["13","15","19","20"], correct:3, explain:"AND requires BOTH conditions to be TRUE. When Age = 20, Age > 12 is TRUE but Age < 20 is FALSE, so the overall condition is FALSE and nothing is output.", topic:"Logical Operators (AND/OR)", difficulty:"moderate" },
        { type:"mcq", q:"Study the pseudocode below. Mark = 45 and Attendance = 70. What is output?", code:"IF Mark < 40 OR Attendance < 75 THEN\n    OUTPUT \"At risk\"\nELSE\n    OUTPUT \"OK\"\nENDIF", options:["At risk","OK","Both messages are output","The program produces an error"], correct:0, explain:"OR only needs ONE condition to be TRUE. Mark < 40 is FALSE, but Attendance < 75 is TRUE (70 < 75), so the overall condition is TRUE and \"At risk\" is output.", topic:"Logical Operators (AND/OR)", difficulty:"moderate" },
        { type:"mcq", q:"What is wrong with the pseudocode extract below?", code:"INPUT Num\nIF Num > 0 THEN\n    OUTPUT \"Positive\"\nIF Num < 0 THEN\n    OUTPUT \"Negative\"\nENDIF", options:["The first IF statement (Num > 0) is missing its own ENDIF","CASE OF should have been used instead of IF","The operator > should have been >=","INPUT should have been OUTPUT"], correct:0, explain:"Every IF statement must be closed with its own ENDIF. The first IF (Num > 0) has no matching ENDIF before the second IF begins, so the structure is incomplete.", topic:"IF Statement Syntax", difficulty:"hard", hint:"Count the IF keywords, then count the ENDIF keywords. Cambridge pseudocode needs exactly one ENDIF to close every IF — go through the extract line by line and see where that pairing breaks down." },
        { type:"mcq", q:"Which condition correctly checks that Mark is a valid percentage between 0 and 100 inclusive?", options:["IF Mark > 0 AND Mark < 100 THEN","IF Mark >= 0 AND Mark <= 100 THEN","IF Mark >= 0 OR Mark <= 100 THEN","IF Mark > 0 OR Mark < 100 THEN"], correct:1, explain:"To include both boundary values (0 and 100), >= and <= must be used, and both conditions must hold at once, so AND is required. OR would be true for almost any number and would not validate the range correctly.", topic:"Logical Operators (AND/OR)", difficulty:"moderate" },
        { type:"mcq", q:"Study the pseudocode below. What is output when Mark = 60?", code:"INPUT Mark\nIF Mark >= 80 THEN\n    Grade <- \"A\"\nELSE\n    IF Mark >= 60 THEN\n        Grade <- \"B\"\n    ELSE\n        Grade <- \"C\"\n    ENDIF\nENDIF\nOUTPUT Grade", options:["A","B","C","No value is output"], correct:1, explain:"60 >= 80 is FALSE, so the program moves to the ELSE branch. There, 60 >= 60 is TRUE, so Grade is set to \"B\", which is then output.", topic:"Nested IF Statements", difficulty:"hard", hint:"Trace it top to bottom: test Mark >= 80 first. Since that's false here, move into the ELSE branch and test the NEXT condition inside it before deciding what gets assigned to Grade." },

        // ---------------- SECTION B: System Development Life Cycle (10) ----------------
        { type:"mcq", q:"Which option lists the stages of the program development life cycle in the correct order?", options:["Design, Analysis, Coding, Testing, Maintenance","Analysis, Design, Coding, Testing, Maintenance","Analysis, Coding, Design, Testing, Maintenance","Coding, Analysis, Design, Testing, Maintenance"], correct:1, explain:"The life cycle follows a logical order: the problem is analysed first, then a solution is designed, then coded, then tested, and finally maintained once it is in use.", topic:"Life Cycle Stages & Order", difficulty:"easy" },
        { type:"mcq", q:"Which of these tasks is carried out during the ANALYSIS stage of the program development life cycle?", options:["Writing the source code in a high-level language","Drawing a structure diagram or flowchart of the solution","Using fact-finding methods to identify the required inputs, processes and outputs","Running the program with test data to find errors"], correct:2, explain:"Analysis is about understanding the problem before any solution is designed. It uses fact-finding methods such as interviews, questionnaires, observation and examining existing documents to establish what the new system must do.", topic:"Analysis Stage", difficulty:"easy" },
        { type:"mcq", q:"Which of these is NOT typically used as a design tool during the DESIGN stage of the program development life cycle?", options:["Structure diagram","Flowchart","Pseudocode","Test data table"], correct:3, explain:"Structure diagrams, flowcharts and pseudocode are all used to design a solution before it is coded. A test data table (normal, abnormal, extreme, boundary data) belongs to the testing stage, not design.", topic:"Design Stage & Tools", difficulty:"moderate" },
        { type:"mcq", q:"A program accepts an integer between 1 and 10 inclusive. Which value is boundary test data that the program should REJECT?", options:["5","1","11","\"ten\""], correct:2, explain:"Boundary data lies on the edge of the acceptable range and includes the value just outside it. 11 is one more than the highest accepted value (10), so it should be rejected. 5 is normal data, 1 is extreme data (an accepted edge value), and \"ten\" is abnormal data (wrong data type).", topic:"Testing & Test Data", difficulty:"moderate" },
        { type:"mcq", q:"During which stage of the program development life cycle would a feasibility study most likely be carried out?", options:["Analysis","Design","Coding","Testing"], correct:0, explain:"A feasibility study is carried out early, during analysis, to judge whether a proposed solution is practical in terms of time, cost, technology and resources before any design work begins.", topic:"Analysis Stage", difficulty:"easy" },
        { type:"mcq", q:"Which of these is an example of TECHNICAL documentation, rather than user documentation?", options:["A troubleshooting guide with FAQs written for the end user","A list of error messages and their meanings, written for the customer","A program listing with a list of variable names and their purposes","Step-by-step instructions on how to install the software"], correct:2, explain:"Technical documentation is aimed at programmers/maintainers of the system and includes items such as the program listing, list of variables, and algorithms. User documentation (the other options) helps the end user operate the program.", topic:"Documentation", difficulty:"hard", hint:"Ask who each option is written FOR. Something written to help a programmer understand, fix or maintain the code is technical documentation; something written to help an end user operate the finished program is user documentation." },
        { type:"mcq", q:"What is the main purpose of the MAINTENANCE stage of the program development life cycle?", options:["To write the program's source code for the first time","To identify the requirements of the new system","To ensure the program continues to work correctly and to correct any errors found after release","To create the structure diagram for the algorithm"], correct:2, explain:"Maintenance happens after the program has been implemented and is in use. It involves fixing errors that appear and keeping the program working correctly over time.", topic:"Maintenance Stage", difficulty:"easy" },
        { type:"mcq", q:"What is the purpose of using a trace table when testing an algorithm?", options:["To record the physical hardware used during testing","To track the values of variables and any output as the algorithm executes, without running it on a computer","To list all the syntax errors found in a program","To document the requirements gathered from the client"], correct:1, explain:"A trace table is used to perform a 'dry run' of an algorithm by hand, recording how each variable's value changes and what is output at each step, to check the logic is correct.", topic:"Testing & Test Data", difficulty:"easy" },
        { type:"mcq", q:"Which of these would most likely be carried out during the EVALUATION stage of the program development life cycle?", options:["Comparing the finished solution against the original requirements to judge how successful it is","Writing pseudocode for the algorithm","Choosing appropriate variable names and data types","Collecting requirements from the client using a questionnaire"], correct:0, explain:"Evaluation takes place once the solution is complete. It involves reviewing the finished program against the original requirements/specification and identifying strengths, weaknesses and possible improvements.", topic:"Evaluation Stage", difficulty:"moderate" },
        { type:"mcq", q:"Which of these is NOT a typical fact-finding method used during the analysis stage?", options:["Interviewing existing system users","Observing how the current system is used","Distributing a questionnaire to stakeholders","Writing the final program code"], correct:3, explain:"Interviews, observation and questionnaires are all fact-finding methods used during analysis. Writing the final code is part of the coding stage, much later in the life cycle.", topic:"Analysis Stage", difficulty:"easy" }
      ]
    },
    algo: {
      key: "algo",
      title: "IGCSE Computer Science 0478 — Topic 7: Algorithm Design & Problem-Solving",
      subtitle: "Paper 2 · Abstraction & decomposition, loops, standard algorithms, validation & verification, test data & trace tables",
      classes: ["10BR1","10BR2","10BR3"],
      sectionA: { label: "Multiple Choice", count: 30 },
      sectionB: { label: "True / False", count: 10 },
      hasGrade: true,
      questions: [
        // ---------------- SECTION A: Multiple Choice (30) ----------------
        { type:"mcq", q:"Which stage of the Program Development Life Cycle (PDLC) involves defining problem requirements, applying abstraction, and decomposing the problem into manageable parts?", options:["Coding and iterative testing","Analysis","Program design","System testing"], correct:1, explain:"Analysis is the first PDLC stage, where requirements are specified using fact-finding methods, abstraction, and decomposition — before any design or coding takes place.", topic:"PDLC Stages", difficulty:"easy" },
        { type:"mcq", q:"A software developer removes unnecessary details from a problem statement to focus only on the essential features required. What is this technique called?", options:["System decomposition","Abstraction","Double entry verification","Boundary testing"], correct:1, explain:"Abstraction means filtering out non-essential details so a solution focuses only on what's actually needed to solve the problem — for example, ignoring an ATM's physical colour when modelling how it processes transactions.", topic:"Abstraction & Decomposition", difficulty:"easy" },
        { type:"mcq", q:"In standard Cambridge IGCSE 0478 flowchart notation, which symbol represents an Input or Output operation?", options:["Rectangle","Diamond","Parallelogram","Oval / Rounded Rectangle"], correct:2, explain:"Flowchart parallelograms strictly represent Input/Output operations; a rectangle represents a process step and a diamond represents a decision.", topic:"Flowchart Symbols", difficulty:"easy" },
        { type:"mcq", q:"A system checks that a student's mark entered into a form lies between 0 and 100 inclusive. Which type of validation check is performed?", options:["Format check","Length check","Range check","Check digit"], correct:2, explain:"A range check verifies that a value lies within an acceptable upper and lower limit — here, between 0 and 100 inclusive.", topic:"Validation Checks", difficulty:"easy" },
        { type:"mcq", q:"Which verification method involves displaying entered data back to the user on screen so they can visually check its accuracy before submission?", options:["Double entry check","Range check","Visual / Screen check","Parity check"], correct:2, explain:"A visual/screen check allows a manual review, where the user inspects the data displayed on screen before confirming it is correct.", topic:"Verification Methods", difficulty:"easy" },
        { type:"mcq", q:"In Cambridge IGCSE 0478 pseudocode, which standard symbol is used as the assignment operator to store a value in a variable?", options:["=","==","<- (left arrow)",":="], correct:2, explain:"Cambridge pseudocode uses the left arrow (<-) as the assignment operator, e.g. Total <- Total + Value. Using = or := instead is penalised in exam questions.", topic:"Pseudocode Syntax", difficulty:"easy" },
        { type:"mcq", q:"Which basic data type should be declared for a variable GradeLetter that stores a single letter such as 'A', 'B', or 'C'?", options:["STRING","CHAR","BOOLEAN","REAL"], correct:1, explain:"CHAR stores a single character (e.g. 'A'), whereas STRING stores multi-character text in double quotes such as \"Pass\".", topic:"Data Types", difficulty:"easy" },
        { type:"mcq", q:"Test data that lies within the acceptable range of a program and is expected to produce correct outputs without error is classified as:", options:["Abnormal data","Extreme data","Normal data","Boundary data"], correct:2, explain:"Normal data lies safely within the valid range and is used to test that the program produces the expected, correct outcome for typical inputs.", topic:"Test Data Types", difficulty:"easy" },
        { type:"mcq", q:"Which loop structure in pseudocode is specifically designed to execute a sequence of statements a fixed, predetermined number of times?", options:["WHILE...DO...ENDWHILE","REPEAT...UNTIL","FOR...TO...NEXT","IF...THEN...ELSE...ENDIF"], correct:2, explain:"FOR...TO...NEXT is a count-controlled loop: the number of repetitions is fixed and known in advance from its start and end values. WHILE and REPEAT loops are condition-controlled and can run a different number of times depending on the data.", topic:"Loop Structures", difficulty:"easy" },
        { type:"mcq", q:"Check digits are calculated and appended to identification codes to detect entry errors. Which of the following commonly uses a check digit?", options:["User passwords","Barcodes and ISBNs","Variable names in source code","Email addresses"], correct:1, explain:"Check digits are used on codes like barcodes and ISBNs to detect data entry errors such as transposed or mistyped digits.", topic:"Check Digits", difficulty:"easy" },
        { type:"mcq", q:"An algorithm validates exam marks from 0 to 100 inclusive. Which pair of values represents boundary test data for the upper limit (100)?", options:["0 and 100","99 and 100","100 and 101","100 and 1000"], correct:2, explain:"Boundary data tests the exact point where acceptance turns to rejection, so it needs one value just inside the limit and one value just outside it. For an upper limit of 100, that's 100 (the last accepted value) and 101 (the first rejected value).", topic:"Boundary & Extreme Test Data", difficulty:"moderate" },
        { type:"mcq", q:"What is the primary purpose of constructing a trace table during a dry run of an algorithm?", options:["To translate pseudocode into Python or VB.NET automatically","To track step-by-step changes in variable values and outputs to catch logic errors","To check if user passwords meet security length rules","To compress data files before saving to secondary storage"], correct:1, explain:"A trace table lets you dry-run an algorithm by hand, recording how each variable's value (and any output) changes at every step, so logic errors can be caught without running the program on a computer.", topic:"Trace Tables & Dry Runs", difficulty:"easy" },
        { type:"mcq", q:"A linear search is executed on the array [4, 8, 2, 15, 9, 30] to locate the target value 15. How many element comparisons will be performed?", options:["1 comparison","4 comparisons","6 comparisons","15 comparisons"], correct:1, explain:"A linear search checks each element in order from the start of the array until it finds the target. 15 is the 4th element in [4, 8, 2, 15, 9, 30], so it takes 4 comparisons (4, 8, 2, then 15) to find it.", topic:"Standard Algorithms: Linear Search", difficulty:"moderate" },
        { type:"mcq", q:"During the first complete pass of a Bubble Sort on an unsorted list of N numbers, what is guaranteed regarding the largest unsorted element?", options:["It moves to the very first position of the array","It bubbles up to its correct final position at the end of the array","It is deleted from the array","It is swapped with the array mean"], correct:1, explain:"On each full pass, a Bubble Sort compares adjacent elements and swaps them if they're out of order. This pushes the largest unsorted element step by step across the array until it 'bubbles up' to its correct final position at the end by the time the pass is complete.", topic:"Standard Algorithms: Bubble Sort", difficulty:"moderate" },
        { type:"mcq", q:"Which pseudocode snippet correctly implements an input validation loop that prompts until an input Score lies within 0 to 50 inclusive?", options:["REPEAT\n    INPUT Score\nUNTIL Score >= 0 AND Score <= 50","REPEAT\n    INPUT Score\nUNTIL Score < 0 OR Score > 50","WHILE Score >= 0 AND Score <= 50 DO\n    INPUT Score\nENDWHILE","REPEAT\n    INPUT Score\nUNTIL Score = 0 OR Score = 50"], correct:0, explain:"A REPEAT...UNTIL loop keeps repeating until its UNTIL condition becomes TRUE, so the loop should stop once Score is actually valid: UNTIL Score >= 0 AND Score <= 50.", topic:"Validation Pseudocode", difficulty:"moderate" },
        { type:"mcq", q:"A system requires a password to be between 8 and 16 characters in length. Which pseudocode condition correctly identifies an invalid password?", options:["IF LENGTH(Password) >= 8 AND LENGTH(Password) <= 16","IF LENGTH(Password) < 8 OR LENGTH(Password) > 16","IF LENGTH(Password) = 8 OR LENGTH(Password) = 16","IF LENGTH(Password) <> 0"], correct:1, explain:"A password is invalid if its length falls outside the accepted range, so the condition needs OR: length less than 8, OR length greater than 16.", topic:"Length Check Logic", difficulty:"moderate" },
        { type:"mcq", q:"Why is a REPEAT...UNTIL post-condition loop often preferred over a WHILE...DO...ENDWHILE pre-condition loop for user data entry validation?", options:["REPEAT...UNTIL checks the condition before executing the loop body","REPEAT...UNTIL guarantees the input prompt runs at least once before testing validity","WHILE...DO loops cannot process Boolean relational operators","REPEAT...UNTIL loops execute a fixed count determined at compile time"], correct:1, explain:"A REPEAT...UNTIL post-condition loop checks its condition after the loop body runs, so the input prompt is always executed at least once — ideal for asking the user for data before it can be validated.", topic:"Loop Comparison", difficulty:"moderate" },
        { type:"mcq", q:"An algorithm intends to count strictly positive numbers (> 0). It contains: IF Num >= 0 THEN Count <- Count + 1. What logic error occurs when 0 is entered?", options:["Syntax error: compiler rejects the operator >=","Logic error: zero is counted as positive even though zero is neither positive nor negative","Runtime error: array index overflow","Division by zero error"], correct:1, explain:"Zero is neutral — neither positive nor negative — but the condition Num >= 0 is TRUE when Num is 0, so it gets counted as positive by mistake. This is a logic error, not a syntax or runtime error.", topic:"Logic Error Identification", difficulty:"hard", hint:"Work out exactly what \"strictly positive\" means (greater than zero, not including zero), then check whether the condition Num >= 0 would let zero slip through as well." },
        { type:"mcq", q:"Which line of pseudocode represents the standard algorithm for totalling values inside a loop?", options:["Count <- Count + 1","Total <- Total + Value","Average <- Total / Count","Total <- Value"], correct:1, explain:"Totalling accumulates values by repeatedly adding each new value to a running total: Total <- Total + Value. Counting instead adds 1 each time (Count <- Count + 1), and an average is only calculated once, after the loop ends, by dividing the total by the count.", topic:"Totalling & Counting Algorithms", difficulty:"easy" },
        { type:"mcq", q:"Which statement best describes the purpose of a structure diagram in system design?", options:["It displays line-by-line programming language syntax and variable declarations","It represents the top-down hierarchical decomposition of a system into sub-systems","It generates truth tables for multi-input logic circuits","It performs automated dry runs of pseudocode"], correct:1, explain:"A structure diagram shows how a system is broken down, top-down, into smaller sub-systems and modules — it's a design tool, not a way to run or test code.", topic:"Structure Diagrams", difficulty:"easy" },
        { type:"mcq", q:"A 2D array is declared as DECLARE Grid : ARRAY[1:3, 1:4] OF INTEGER. How many total elements can it store, and what does Grid[2, 3] represent?", options:["7 elements; Row 3, Column 2","12 elements; Row 2, Column 3","12 elements; Row 3, Column 2","14 elements; Column 2, Row 3"], correct:1, explain:"ARRAY[1:3, 1:4] has 3 rows and 4 columns, giving 3 x 4 = 12 elements in total. By convention Grid[row, column], so Grid[2, 3] is Row 2, Column 3.", topic:"2D Array Indexing", difficulty:"hard", hint:"Multiply the two dimensions together first to get the total element count. Then, for Grid[2, 3], remember Cambridge pseudocode always lists the ROW index before the COLUMN index." },
        { type:"mcq", q:"An exam grading system assigns 'Pass' for marks >= 50 and 'Fail' for marks < 50. Which pair of boundary test data values specifically tests this Pass/Fail threshold boundary?", options:["0 and 100","49 and 50","50 and 51","49 and 51"], correct:1, explain:"The Pass/Fail threshold sits exactly between 49 and 50, so boundary testing needs the highest failing value (49) and the lowest passing value (50).", topic:"Boundary Testing Thresholds", difficulty:"moderate" },
        { type:"mcq", q:"Trace the pseudocode below. What are the final values of X and Y when the loop terminates?", code:"X <- 5\nY <- 2\nWHILE X > Y DO\n    X <- X - 1\n    Y <- Y + 1\nENDWHILE", options:["X = 3, Y = 4","X = 2, Y = 5","X = 3, Y = 3","X = 4, Y = 3"], correct:0, explain:"Trace it step by step: start X=5, Y=2. Pass 1 (5>2 TRUE): X=4, Y=3. Pass 2 (4>3 TRUE): X=3, Y=4. Now 3>4 is FALSE, so the loop ends with X = 3, Y = 4.", topic:"Trace Table Trace Analysis", difficulty:"hard", hint:"Draw a small trace table with columns for X, Y and the condition X > Y. Update X and Y one line at a time and re-check the condition after every pass, rather than trying to do it in your head." },
        { type:"mcq", q:"A candidate writes a Bubble Sort loop for ARRAY[1:10]:", code:"FOR Index <- 1 TO 10\n    IF Array[Index] > Array[Index + 1] THEN ...", options:["Array indices cannot be manipulated mathematically","When Index = 10, Array[Index + 1] attempts to access Array[11], which exceeds the upper bound","Bubble Sort requires a 2D array structure","The FOR loop should start at Index = 0"], correct:1, explain:"The array only holds valid indices 1 to 10. When Index reaches 10, Array[Index + 1] tries to read Array[11], which doesn't exist — an out-of-bounds error. The loop should run FOR Index <- 1 TO 9 instead.", topic:"Array Index Bounds in Loops", difficulty:"hard", hint:"Work out the very last value Index takes inside the FOR loop, then check what Array[Index + 1] would be trying to read at that point — does a position that far along the array actually exist?" },
        { type:"mcq", q:"Given string variable Word <- \"COMPUTER\", what string value is returned by the pseudocode function call SUBSTRING(Word, 4, 3) (where 4 is start position and 3 is length)?", options:["\"COM\"","\"PUT\"","\"PUTE\"","\"UT\""], correct:1, explain:"SUBSTRING(\"COMPUTER\", 4, 3) starts counting from position 4 — the letter 'P' — and takes 3 characters: 'P', 'U', 'T', giving \"PUT\".", topic:"String Handling Functions", difficulty:"moderate" },
        { type:"mcq", q:"To find both the Maximum and Minimum values in an array [1:N] in a single pass, how should the variables Max and Min be initialized before the loop?", options:["Max <- 0, Min <- 0","Max <- Array[1], Min <- Array[1]","Max <- 100, Min <- 0","Max <- -1, Min <- 1000"], correct:1, explain:"Initialising Max and Min to arbitrary numbers like 0 fails if every array value is negative (or larger than the assumed maximum). Setting Max <- Array[1] and Min <- Array[1] before the loop guarantees a valid starting point drawn from the array itself.", topic:"Min/Max Initialization", difficulty:"moderate" },
        { type:"mcq", q:"A UK postal code requires the pattern '2 letters, 2 digits, space, 1 digit, 2 letters' (e.g. AB12 3CD). Why is a Type Check alone insufficient to validate this input?", options:["A Type check cannot evaluate string variables","A Type check only checks the overall data type (STRING), but cannot enforce the specific mixed pattern of character types required (Format Check)","A Type check only accepts integer inputs","A Type check automatically converts letters to numbers"], correct:1, explain:"A type check only confirms the data is the right general type, such as STRING. It cannot enforce a specific pattern of letters, digits and spaces — that needs a format check instead.", topic:"Type Check vs Format Check", difficulty:"moderate" },
        { type:"mcq", q:"What are the exact integer outputs of DIV(17, 5) and MOD(17, 5) respectively in Cambridge pseudocode?", options:["3 and 2","3.4 and 2","2 and 3","3 and 0.4"], correct:0, explain:"DIV gives the integer (whole-number) quotient: 17 DIV 5 = 3. MOD gives the remainder left over: 17 MOD 5 = 2 (since 3 x 5 = 15, and 17 - 15 = 2).", topic:"Modular Division Operators", difficulty:"moderate" },
        { type:"mcq", q:"A user enters their date of birth as 12/05/2005 instead of their actual birth date 15/02/2005. Both dates are formatted correctly and within valid ranges. Which statement is correct?", options:["Validation will reject the entry because the numbers do not match reality","Validation cannot detect this error because 12/05/2005 is reasonable and correctly formatted; Verification (e.g. double entry or visual check) is needed","A check digit will flag the discrepancy in month","A presence check will trigger an error message"], correct:1, explain:"Validation only checks that data is reasonable and correctly formatted — it cannot know whether the date is factually true. Catching a wrong-but-plausible value like this needs verification, such as a double-entry or visual check against the original source.", topic:"Validation vs Verification Limitations", difficulty:"hard", hint:"Ask whether 12/05/2005 is a real, correctly-formatted date in its own right — if a validation check would happily accept it, the mistake needs a different kind of check to catch it instead." },
        { type:"mcq", q:"An array [1, 2, 3, 4, 5] (already sorted) is processed by an optimized Bubble Sort algorithm using a boolean flag Swap. How many comparisons occur on Pass 1, and does a Pass 2 take place?", options:["4 comparisons; Swap remains FALSE, so the loop terminates immediately after Pass 1","5 comparisons; the algorithm makes 5 full passes regardless of sorting","0 comparisons; sorted arrays bypass the loop","4 comparisons; Swap becomes TRUE"], correct:0, explain:"An optimized Bubble Sort resets Swap to FALSE at the start of each pass. Pass 1 makes 4 comparisons across the already-sorted array and finds nothing to swap, so Swap stays FALSE and the algorithm halts immediately — no Pass 2 is needed.", topic:"Bubble Sort Optimization", difficulty:"hard", hint:"Count how many adjacent pairs get compared across the whole array in one pass, then think about what the Swap flag is checked against at the very end of a pass to decide whether another pass is needed." },

        // ---------------- SECTION B: True / False (10) ----------------
        { type:"tf", q:"Abstraction in problem-solving involves filtering out unnecessary details to focus strictly on the essential components needed to solve the problem.", options:["True","False"], correct:0, explain:"This is exactly what abstraction means: keeping only the details that matter for solving the problem and ignoring the rest.", topic:"Abstraction & Decomposition", difficulty:"easy" },
        { type:"tf", q:"A WHILE...DO...ENDWHILE pre-condition loop is guaranteed to execute its loop body statements at least once.", options:["True","False"], correct:1, explain:"A WHILE loop checks its condition BEFORE the body runs, so if the condition is FALSE to begin with, the body executes zero times. Only a REPEAT...UNTIL post-condition loop guarantees at least one execution.", topic:"Loop Structures", difficulty:"moderate" },
        { type:"tf", q:"Validation checks ensure that data entered by the user is completely accurate, truthful, and matches real-world facts.", options:["True","False"], correct:1, explain:"Validation only checks that data is reasonable and correctly formatted — it cannot confirm the data reflects real-world truth. That level of checking needs verification instead.", topic:"Validation Checks", difficulty:"moderate" },
        { type:"tf", q:"Extreme test data consists of the largest and smallest acceptable values within a valid range.", options:["True","False"], correct:0, explain:"Extreme data represents the values right at the edges of the valid range that are still accepted — for a range of 0 to 100, that's 0 and 100.", topic:"Test Data Types", difficulty:"easy" },
        { type:"tf", q:"In Cambridge IGCSE 0478 pseudocode, the standard symbol for the assignment operator is =.", options:["True","False"], correct:1, explain:"The standard Cambridge assignment operator is the left arrow (<-), not =. Using = for assignment is a common mistake that loses marks.", topic:"Pseudocode Syntax", difficulty:"easy" },
        { type:"tf", q:"Double entry is a method of data validation performed automatically by the computer system.", options:["True","False"], correct:1, explain:"Double entry is a verification method — typically requiring data to be entered twice (often by different people) so the two copies can be compared — not an automated validation check.", topic:"Verification Methods", difficulty:"easy" },
        { type:"tf", q:"A trace table is used during a dry run of an algorithm to record line-by-line changes in variable values and output statements.", options:["True","False"], correct:0, explain:"That's exactly what a trace table does: it records how each variable changes, and what is output, as the algorithm is worked through by hand.", topic:"Trace Tables & Dry Runs", difficulty:"easy" },
        { type:"tf", q:"In a linear search algorithm, array elements must be sorted in ascending order before the search can be performed.", options:["True","False"], correct:1, explain:"A linear search checks every element in turn from the start of the array, so it works correctly on both sorted and unsorted data. Only a binary search requires the data to be sorted first.", topic:"Standard Algorithms: Linear Search", difficulty:"moderate" },
        { type:"tf", q:"The decision symbol (diamond) in a standard flowchart has one input flow line and two output flow lines representing True/False or Yes/No paths.", options:["True","False"], correct:0, explain:"A decision diamond takes one flow line in and produces two flow lines out, one for each possible outcome of the condition (True/False or Yes/No).", topic:"Flowchart Symbols", difficulty:"easy" },
        { type:"tf", q:"System decomposition involves combining several small sub-systems into one large monolithic program.", options:["True","False"], correct:1, explain:"Decomposition is the opposite: it breaks a large, complex system down into smaller, more manageable sub-systems, rather than combining smaller pieces into one big program.", topic:"Abstraction & Decomposition", difficulty:"easy" }
      ]
    }
  };

  // Which exam(s) a class can practise. Most classes map straight to one
  // exam; 10BR classes have two IGCSE topics to choose between, so the
  // quiz page shows a second "Topic" dropdown built from this list.
  var EXAM_CHOICES_BY_CLASS = [
    { test: /^10am/i, choices: [
      { key: "dp" }
    ] },
    { test: /^10br/i, choices: [
      { key: "algo", label: "Topic 7: Algorithm Design & Problem-Solving" },
      { key: "igcse", label: "Conditional Statements practice questions" }
    ] }
  ];

  function examChoicesForClass(cls){
    for(var i = 0; i < EXAM_CHOICES_BY_CLASS.length; i++){
      if(EXAM_CHOICES_BY_CLASS[i].test.test(cls)) return EXAM_CHOICES_BY_CLASS[i].choices;
    }
    return [];
  }

  // Back-compat single-answer helper: the class's default/only exam.
  // When a class has more than one choice, prefer examChoicesForClass()
  // plus an explicit topic selection instead of this.
  function examKeyForClass(cls){
    var choices = examChoicesForClass(cls);
    return choices.length ? choices[0].key : null;
  }

  function examQuestions(examKey){ return EXAMS[examKey].questions; }

  // Display label for a question's difficulty. The internal value stored
  // on each question ("easy"/"moderate"/"hard" -- also the suffix on the
  // diff-badge/--diff-* CSS names) stays as-is so the styling and marks
  // logic (questionMarks() in report-lib.js) don't need to change, but
  // "moderate" is shown to students/teachers as "Intermediate".
  var DIFFICULTY_LABELS = { easy: "Easy", moderate: "Intermediate", hard: "Hard" };
  function difficultyLabel(d){
    return DIFFICULTY_LABELS[d] || (d ? d.charAt(0).toUpperCase() + d.slice(1) : "");
  }
