  var EXAMS = {
    dp: {
      key: "dp",
      title: "Data Privacy Practice",
      subtitle: "Sprint 1.4 · Unit 1: Technology, IP and Security · DigiChamps Level 10",
      classes: ["10AM1","10AM2","10AM3","10AM4","10AM5","10AM6"],
      sectionA: { label: "Multiple choice", count: 20 },
      sectionB: { label: "True / False", count: 10 },
      hasGrade: false,
      questions: [
        // ---------------- MULTIPLE CHOICE (20) ----------------
        { type:"mcq", q:"Which best describes “automated data collection”?", options:["Collecting data automatically, often without users’ full knowledge or consent","A method where users manually approve every single data point collected","A process that only happens with written government permission","Deleting user data automatically after every session"], correct:0, explain:"Automated data collection can happen quietly in the background — for example, apps mining account activity or cameras analysing shopper behaviour — often without people realising it.", topic:"Automated Data Collection" },
        { type:"mcq", q:"Which organisation was accused in 2018 of harvesting data from up to 87 million Facebook users without their consent?", options:["Yahoo","Cambridge Analytica","Microsoft","The Network Advertising Initiative"], correct:1, explain:"Cambridge Analytica combined this data with voter information and psychological profiling to target political ads and influence public opinion.", topic:"Cambridge Analytica Case" },
        { type:"mcq", q:"How did Cambridge Analytica initially obtain much of its data?", options:["Through a personality-quiz app connected to Facebook’s API","By hacking government servers","Through a public records request","From a leaked Yahoo database"], correct:0, explain:"The app could access data from people who took the quiz and, through the same permission, data about their friends too — even without the friends' own consent.", topic:"Cambridge Analytica Case" },
        { type:"mcq", q:"What is “profiling” in a data-privacy context?", options:["Verifying someone’s identity with a photo ID","Encrypting a user’s personal files","Analysing personal data to categorise or predict someone’s behaviour and preferences","Deleting inactive accounts"], correct:2, explain:"Profiling uses information such as browsing history, purchases, and demographics to make predictions — it's behind things like targeted ads and credit scoring.", topic:"Profiling & Surveillance" },
        { type:"mcq", q:"Which of these is an example of profiling described in the material?", options:["Browsing for a t-shirt online and then seeing more shirt ads afterward","Receiving a routine software update notification","Getting a two-factor authentication code by text","A teacher grading an exam"], correct:0, explain:"This is a common result of profiling: past browsing and purchase behaviour shapes the ads a person is shown later.", topic:"Profiling & Surveillance" },
        { type:"mcq", q:"What is one privacy concern with surveillance cameras in stores and on roads?", options:["They cannot legally be installed","People are often unaware their behaviour is being recorded and analysed","They only work during business hours","They require the subject’s written consent every time"], correct:1, explain:"Even when footage seems anonymous, video analytics can still connect it to habits, appearances, and other identifying details.", topic:"Profiling & Surveillance" },
        { type:"mcq", q:"Why does data privacy matter for individual freedom, according to the material?", options:["It lets people control what personal information they share and with whom","It has no connection to personal freedom","It only benefits large corporations","It is solely a legal formality with no real impact"], correct:0, explain:"Privacy lets people set boundaries around their information; without it, trust in relationships and institutions can break down.", topic:"Legal, Social & Economic Implications" },
        { type:"mcq", q:"What challenge do differing global privacy laws create for international companies?", options:["None — all countries follow the exact same rules","Conflicting compliance and enforcement requirements across regions","Companies are banned from collecting any data","It eliminates the need for privacy policies"], correct:1, explain:"Some countries regulate data collection tightly while others favour open access, creating incompatible standards for companies operating across borders.", topic:"Legal, Social & Economic Implications" },
        { type:"mcq", q:"Which of the following is listed as a POSITIVE impact of data use?", options:["Identity theft","Enhanced personalisation of products and services","Discrimination and bias","Widening the digital divide"], correct:1, explain:"Data lets companies understand customer needs closely enough to build more personalised, satisfying products and services.", topic:"Ethical Perspectives (Pros & Cons)" },
        { type:"mcq", q:"Which of the following is listed as a NEGATIVE impact of data misuse?", options:["Improved decision-making","Economic growth","Vulnerability to fraud and identity theft","Better public services"], correct:2, explain:"Sensitive data that is poorly managed can be exploited for fraud, identity theft, and manipulation.", topic:"Ethical Perspectives (Pros & Cons)" },
        { type:"mcq", q:"What does “digital divide” refer to in this context?", options:["A disagreement between two tech companies","Growing inequity for people who lack access to, or literacy with, digital tools","A type of data encryption","A privacy law passed in one country"], correct:1, explain:"As more opportunities depend on data and digital access, people without that access or know-how risk being left further behind.", topic:"Ethical Perspectives (Pros & Cons)" },
        { type:"mcq", q:"What is a data breach?", options:["A scheduled software update","Unauthorised access to, sharing of, or theft of sensitive or protected information","A backup copy of a database","A new privacy regulation"], correct:1, explain:"Breaches can happen through cyberattacks, theft, or simple human error, and can expose personal information on a massive scale.", topic:"Data Breaches" },
        { type:"mcq", q:"Which company’s breach (occurring 2013–2016) exposed data from over 3 billion accounts?", options:["Microsoft","Yahoo","Cambridge Analytica","A retail surveillance company"], correct:1, explain:"The exposed data included names, emails, phone numbers, birth dates, passwords, and security questions.", topic:"Data Breaches" },
        { type:"mcq", q:"The Microsoft Exchange email server attack affected roughly how many US organisations?", options:["About 30,000, from small businesses to local governments","Exactly 100 large corporations only","No real organisations","Only individual home users"], correct:0, explain:"The attack gave hackers access to email accounts across a wide range of organisations, not just large enterprises.", topic:"Data Breaches" },
        { type:"mcq", q:"In the Activity, someone creates a fake Facebook account using Eric’s name and photo. This is best described as:", options:["A form of identity theft / impersonation","A standard security feature","A type of two-factor authentication","A coincidence with no privacy impact"], correct:0, explain:"The impersonator could deceive Eric's contacts and misuse his identity, which is a serious privacy and reputational harm.", topic:"Real-World Scenarios" },
        { type:"mcq", q:"According to the suggested solution, what should Eric do first about the fake account?", options:["Report the fake account to Facebook","Delete his real account","Give the impersonator his login details to “prove” he's real","Ignore it — it will resolve itself"], correct:0, explain:"Reporting the impersonating account is the first recommended step, along with warning friends and reviewing his own privacy settings.", topic:"Real-World Scenarios" },
        { type:"mcq", q:"What is recommended when you must use sensitive services (like banking) on public Wi-Fi?", options:["Turn off your phone’s lock screen","Use a Virtual Private Network (VPN) to encrypt your connection","Share the Wi-Fi password with more people","Disable your antivirus software"], correct:1, explain:"Public Wi-Fi is vulnerable to hacking, and a VPN encrypts your traffic so it's harder to intercept.", topic:"Protecting Your Privacy" },
        { type:"mcq", q:"In Challenge 1, which feature helps stop unauthorised people from accessing Ms. Anna’s new phone?", options:["Screen lock (PIN, password, pattern, or biometric)","Uninstalling every app","Turning on location services for all apps","Disabling all passwords for convenience"], correct:0, explain:"A secure screen lock is one of the most basic and effective ways to prevent unauthorised access to a device.", topic:"Real-World Scenarios" },
        { type:"mcq", q:"In Challenge 2, how can John reduce the targeted ads he keeps seeing?", options:["Adjust ad-personalisation settings and use privacy tools like ad blockers","Buy more items so the algorithm “gives up”","Post his personal data publicly","Permanently disconnect his phone from the internet"], correct:0, explain:"Turning off ad personalisation where available, using ad blockers, and clearing cookies all help reduce targeted advertising.", topic:"Real-World Scenarios" },
        { type:"mcq", q:"In Challenge 3, what is the first step recommended for Sophia to audit her social media privacy?", options:["Delete every social media account","List all the platforms she’s active on and review each one’s privacy settings","Make every post public so she can “see what happens”","Share her passwords with close friends for backup"], correct:1, explain:"Auditing starts with knowing exactly which platforms you use, then reviewing each one’s privacy policy and settings.", topic:"Real-World Scenarios" },

        // ---------------- TRUE / FALSE (10) ----------------
        { type:"tf", q:"Automated data collection can happen without users being aware of it or giving explicit consent.", options:["True","False"], correct:0, explain:"Examples include social platforms mining account data quietly and surveillance cameras analysing behaviour without direct notice.", topic:"Automated Data Collection" },
        { type:"tf", q:"The people whose data Cambridge Analytica used had all given full, informed consent for that use.", options:["True","False"], correct:1, explain:"The data was collected and used without the knowledge or permission of most of the people affected — including friends of quiz-takers.", topic:"Cambridge Analytica Case" },
        { type:"tf", q:"Profiling is used only for harmful purposes and has no legitimate applications.", options:["True","False"], correct:1, explain:"Profiling also supports legitimate uses like fraud detection and personalised recommendations, alongside real risks like discrimination.", topic:"Profiling & Surveillance" },
        { type:"tf", q:"Because surveillance footage is often anonymous, it can never be used to identify or target specific individuals.", options:["True","False"], correct:1, explain:"Video analytics can still connect footage to habits, appearances, and other identifying details, even without a name attached.", topic:"Profiling & Surveillance" },
        { type:"tf", q:"Data privacy laws and regulations differ from country to country based on social, economic, and cultural factors.", options:["True","False"], correct:0, explain:"Some countries regulate data collection tightly to protect privacy, while others favour open data access to encourage innovation.", topic:"Legal, Social & Economic Implications" },
        { type:"tf", q:"Government use of data for public-safety purposes is mentioned as one of the positive impacts of data use.", options:["True","False"], correct:0, explain:"Improved crime prevention, emergency response, and security outcomes are listed as potential benefits, alongside the risks of excessive surveillance.", topic:"Ethical Perspectives (Pros & Cons)" },
        { type:"tf", q:"The Yahoo breach (2013–2016) is described as one of the largest data breaches in history.", options:["True","False"], correct:0, explain:"It affected over 3 billion accounts, exposing details like names, emails, phone numbers, and passwords.", topic:"Data Breaches" },
        { type:"tf", q:"Using the same simple password for every account is a recommended way to protect your privacy.", options:["True","False"], correct:1, explain:"Unique, complex passwords for each account are recommended instead — reused passwords put every account at risk if just one is exposed.", topic:"Protecting Your Privacy" },
        { type:"tf", q:"Enabling two-factor (multi-factor) authentication adds an extra layer of security beyond a password alone.", options:["True","False"], correct:0, explain:"It requires a second form of verification, such as a code sent to your phone, making accounts harder to break into.", topic:"Protecting Your Privacy" },
        { type:"tf", q:"Regularly updating your devices and apps has no real effect on protecting your privacy or security.", options:["True","False"], correct:1, explain:"Updates often include security patches that close vulnerabilities attackers could otherwise exploit.", topic:"Protecting Your Privacy" }
      ]
    }
  };

  function examKeyForClass(cls){
    if(/^10am/i.test(cls)) return "dp";
    return null;
  }

  function examQuestions(examKey){ return EXAMS[examKey].questions; }
